config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "postboxes#new"

  get "/postboxes", to: "postboxes#new"
  get "/:uid", to: "postboxes#show"

  resources :postboxes, param: :uid, only: [:show, :create, :destroy, :edit, :update] do
    resources :posts, only: [:index, :create]
  end

  post "/session/login", to: "sessions#create"
  delete "/session/logout", to: "sessions#destroy"

  get "/static_pages/about", to: "static_pages#about"
  get "/static_pages/privacy", to: "static_pages#privacy"
  get "/static_pages/discramer", to: "static_pages#discramer"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :content,  presence: true

  belongs_to :postbox
end

app/models/postbox.rb
# frozen_string_literal: true

class Postbox < ApplicationRecord
  has_secure_password validations: false
  validates :password,
            length: { minimum: 6, too_short: "は6文字以上40文字以下で入力してください。",
                      maximum: 40, too_long: "は6文字以上40文字以下で入力してください。" },
            confirmation: true, on: :create

  validates :uid,  presence: true
  validates :title,  presence: { message: "を入力してください。" },
            length: { maximum: 100, too_long: "は最大40文字まで入力できます。" }
  validates :description,  presence: { message: "を入力してください。" },
            length: { maximum: 200, too_long: "は最大200文字まで入力できます。" }
  validates :slack_webhook_url,
            format: {
                      allow_blank: true,
                      with: /\Ahttps:\/\/hooks\.slack\.com\/services\/.*/,
                      message: "の形式が正しくありません。"
                    }

  has_many :posts

  before_validation do
    self.uid = SecureRandom.urlsafe_base64(20)
  end

  def to_param
    uid
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/postboxes_controller.rb
# frozen_string_literal: true

class PostboxesController < ApplicationController
  include SessionsHelper

  before_action :set_postbox, only: [:show, :edit, :update, :destroy]
  before_action :require_admin_login, only: [:edit, :update, :destroy]

  def index
    @postboxes = Postbox.all
  end

  def show
  end

  def new
    @postbox = Postbox.new
  end

  def create
    @postbox = Postbox.new(postbox_params)
    if @postbox.save
      redirect_to postbox_path(uid: @postbox.uid), notice: "#{@postbox.title}を作成しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @postbox.update(update_postbox_params)
      redirect_to postbox_path(uid: @postbox.uid), notice: "#{@postbox.title}を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @postbox.destroy
    redirect_to root_path, notice: "#{@postbox.title}を削除しました"
  end

  def to_param
    self.uid
  end

  private
    def set_postbox
      @postbox = Postbox.find_by!(uid: params[:uid])
    end

    def postbox_params
      params.require(:postbox).permit(:title, :description, :password, :password_confirmation)
    end

    def update_postbox_params
      params.require(:postbox).permit(:title, :description, :slack_webhook_url)
    end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  include SessionsHelper

  before_action :set_postbox, only: [:index, :create]
  before_action :require_admin_login, only: [:index]

  def index
    respond_to do |format|
      format.csv { csv_export(@postbox) }
      format.json { json_export(@postbox) }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = @postbox.posts.build(post_params)
    if @post.save
      notify_to_slack(@postbox, @post)
      redirect_to postbox_path(@postbox.uid), notice: "入力した内容を投稿しました。投稿内容は投書箱を作成した管理者のみが閲覧できます。"
    else
      redirect_to postbox_path(@postbox.uid), alert: @post.errors.full_messages_for(:content)
    end
  end

  private
    def post_params
      params.permit(:content)
    end

    def set_postbox
      @postbox = Postbox.find_by(uid: params[:postbox_uid])
    end

    def notify_to_slack(postbox, post)
      if postbox.slack_webhook_url.present?
        username = "AnoPost"
        attachments = [{
          title: postbox.title,
          title_link: "#{root_url}#{postbox.uid}",
          fallback: "comment body.",
          author_name: "AnoPost",
          author_icon: "https://raw.githubusercontent.com/wawawatataru/anopost/master/app/assets/images/android-chrome-256x256.png",
          text: post.content,
        }]
        url = postbox.slack_webhook_url
        notifier = Slack::Notifier.new url, username: username
        notifier.ping "#{postbox.title}に投稿がありました。", attachments: attachments
      end
    end

    def csv_export(postbox)
      require "csv"
      csv_data = CSV.generate do |csv|
        csv_column_names = ["投稿内容", "投稿時間"]
        csv << csv_column_names
        postbox.posts.each do |post|
          csv_column_values = [
            post.content,
            post.created_at.strftime("%Y/%-m/%-d %-H:%-M:%-S"),
          ]
          csv << csv_column_values
        end
      end
      send_data(csv_data, filename: "posts.csv")
    end

    def json_export(postbox)
      posts = []
      postbox.posts.each do |post|
        posts.push(content: post.content, date: post.created_at.strftime("%Y/%-m/%-d %-H:%-M:%-S"))
      end
      send_data(posts.to_json, filename: "posts.json")
    end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  include SessionsHelper
  def create
    postbox = Postbox.find_by(uid: params[:uid])
    if postbox && postbox.authenticate(params[:password])
      log_in postbox
      redirect_to edit_postbox_path(postbox.uid), notice: "管理者としてログインしました。"
    else
      redirect_to postbox_path(postbox.uid), alert: ["パスワードが正しくありません。"]
    end
  end

  def destroy
    log_out
    redirect_to root_path, notice: "ログアウトしました。"
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def about
  end

  def privacy
  end

  def discramer
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include SessionsHelper

  def page_title
    title = "AnoPost"
    title = @page_title + " | " + title if @page_title
    title
  end

  def show_or_edit_postbox_page?
    controller_path == "postboxes" && ((action_name == "show") || (action_name == "edit"))
  end
end

app/helpers/meta_tags_helper.rb
# frozen_string_literal: true

module MetaTagsHelper
  def default_meta_tags
    {
      site: "AnoPost",
      title: "AnoPost",
      reverse: true,
      charset: "utf-8",
      description: "AnoPostは企業倫理ホットラインを簡単に作成できるWebサービスです。",
      keywords: "企業倫理,ホットライン,匿名,投書箱",
      canonical: request.original_url,
      separator: "|",
      og: {
        site_name: "AnoPost",
        title: "AnoPost",
        description: "AnoPostは企業倫理ホットラインを簡単に作成できるWebサービスです。",
        type: "website",
        url: root_url,
        image: image_url("apple-touch-icon.png"),
        locale: "ja_JP",
      },
      twitter: {
        card: "summary",
      }
    }
  end
end

app/helpers/postboxs_helper.rb
# frozen_string_literal: true

module PostboxsHelper
  def postbox_submit_label(from)
    if from == :new
      "作成"
    else
      "更新"
    end
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(postbox)
    session[:postbox] = postbox.uid
  end

  def current_postbox
    if session[:postbox]
      @current_postbox ||= Postbox.find_by(uid: session[:postbox])
    end
  end

  def log_out
    session.delete(:postbox)
    @current_postbox = nil
  end

  def logged_in?
    current_postbox.present?
  end

  def require_admin_login
    unless admin_login?
      redirect_to root_path, alert: ["管理者としてログインしてください"]
    end
  end

  def admin_login?
    logged_in? && @postbox.uid == session[:postbox]
  end
end

app/views/application/_admin-link.html.slim
.admin-link-box
  - if @postbox != current_postbox
    input#admin-link type="checkbox"
    label.admin-link__text for="admin-link"
    .hidden-admin-form
      = form_with url: session_login_path(uid: @postbox.uid), local: true do |f|
        .hidden-admin-form__form-group
          = f.label "パスワード", class: "hidden-admin-form__label"
          = f.password_field :password, class: "hidden-admin-form__text-field"
          = f.submit "ログイン", class: "hidden-admin-form__button"
  - else
    - if controller.controller_name == "postboxes" && controller.action_name == "edit"
      = link_to "投書箱に戻る", postbox_path(uid: @postbox.uid), class: "admin-link-box__text"
    - else
      = link_to "管理者ページ", edit_postbox_path(uid: @postbox.uid), class: "admin-link-box__text"
    = link_to "ログアウト", session_logout_path, method: :delete, class: "admin-link-box__text"

app/views/application/_favicon.html.slim
link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png"
link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png"
link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16x16.png"
link rel="mask-icon" href="/assets/safari-pinned-tab.svg" color="#928bfb"
meta name="msapplication-TileColor" content="#928bfb"
meta name="theme-color" content="#ffffff"

app/views/application/_footer.html.slim
footer.footer
  .footer__content
    = link_to root_path, class: "footer-logo-link" do
      .footer-logo
        = image_tag "anopost_logo_footer.svg", alt: "タイトルロゴ", class: "footer-logo__icon"
        p.footer-logo__app-name = t :app_name
    ul.footer-link
      li.footer-link__item
        = link_to "AnoPostとは", static_pages_about_path, class: "footer-link__text"
      li.footer-link__item
        = link_to "Cookieポリシー", static_pages_privacy_path, class: "footer-link__text"
      li.footer-link__item
        = link_to "免責事項", static_pages_discramer_path, class: "footer-link__text"
    = link_to "https://github.com/wawawatataru/anopost", class: "footer-github-link" do
      p.footer-copy &copy;wawawatataru
      .footer-icon = icon "fab", "github"

app/views/application/_header.html.slim
header.header
  .header__content
    = link_to root_path, class: "header-logo-link" do
      .header-logo
        = image_tag "anopost_logo.svg", alt: "タイトルロゴ", class: "header-logo__icon"
        h1.header-logo__app-name = t :app_name
    - if show_or_edit_postbox_page?
      = render "admin-link"

app/views/application/_meta.html.slim
meta name="viewport" content="width=device-width, initial-scale=1.0"
= display_meta_tags(default_meta_tags)

app/views/layouts/application.html.slim
doctype html
html
  head
    title = page_title
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
    = render "favicon"
    = render "meta"
  body
    - unless current_page?(root_path)
      = render "header"
    .content
      - if flash.notice.present?
        .alert.alert-success
          = flash.notice
      - if flash.alert.present?
        .alert.alert-warning
          - flash.alert.each do |alert|
            = alert
      = yield
    = render "footer"
    - if Rails.env.development?
      = debug(params)

app/views/postboxes/_form.html.slim
= form_with model: postbox, local: true do |f|
  .form-group
    = f.label :title, class: "form__label"
    p.form__sub-label URLを知っているすべてのユーザーに公開されます。(最大100文字)
    = f.text_field :title, class: "form__text-field js-count-form", placeholder: "みんなのホットライン", maxlength: "100"
    p.js-count-text

  .form-group
    = f.label :description, class: "form__label"
    p.form__sub-label URLを知っているすべてのユーザーに公開されます。(最大200文字)
    = f.text_area :description, class: "form__text-area js-count-form", placeholder: "社内での倫理違反行為や不正を発見した際はこちらのホットラインでお知らせください", maxlength: "200"
    p.js-count-text

  - if from == :new
    .form-group
        = f.label :password, class: "form__label"
        p.form__sub-label
          |6文字以上のパスワードを入力してください。(最大40文字)
          br
          |パスワードを知っている方はすべての投稿を確認できます。
        = f.password_field :password, class: "form__text-field js-count-form", maxlength: "40"
        p.js-count-text
    .form-group
        = f.label :password_confirmation, class: "form__label"
        p.form__sub-label
          |確認のため再度パスワードを入力してください。
        = f.password_field :password_confirmation, class: "form__text-field"

  - if from == :edit
    .form-group
        = f.label :slack_webhook_url, class: "form__label"
        p.form__sub-label 投稿された内容をSlackにも通知することができます。公開範囲にご注意ください。
        = f.text_field :slack_webhook_url, class: "form__text-field"

  .form-button-group
    = f.submit postbox_submit_label(from), class: "form__button"
    - if from == :edit
      = link_to "削除", postbox_path, method: :delete, data: { confirm: "投書箱を削除してよろしいですか？" }, class: "form__delete-button"

app/views/postboxes/_posts.html.slim
.posts
    - if @postbox.posts.empty?
      p.posts-item__none-text まだ投稿がありません。
    - else
      p.export-description 投稿された内容はCSV形式、JSON形式でダウンロードすることができます。
      .export-buttons
        = link_to postbox_posts_path(postbox_uid: @postbox.uid, format: :csv), class: "export-button--csv" do
          .export-button__icon = icon "fas", "file-export"
          p.export-button__text CSV
        = link_to postbox_posts_path(postbox_uid: @postbox.uid, format: :json), class: "export-button--json" do
          .export-button__icon = icon "fas", "file-export"
          p.export-button__text JSON
      .posts__list
        - @postbox.posts.each do |post|
          .posts-item
            p.posts-item__date = post.created_at.strftime("%Y/%m/%d %H:%M")
            p.posts-item__content = safe_join(post.content.split("\n"), tag(:br))

app/views/postboxes/edit.html.slim
- if @postbox.errors.any?
  .alert.alert-warning
    - @postbox.errors.full_messages.each do |msg|
      p.alert__message = msg
.edit-tab
  p.edit-tab__description このページは管理者のみが見れます。
  input#posts-tab type="radio" name="edit-tab__item" checked=true
  label.edit-tab__item.edit-tab__item-posts for="posts-tab" 投稿一覧
  input#form-tab type="radio" name="edit-tab__item"
  label.edit-tab__item.edit-tab__item-form for="form-tab" 設定
  #posts-tab__content.edit-tab__content
    = render "posts"
  #form-tab__content.edit-tab__content
    .postbox-form
      = render "form", from: :edit, url: edit_postbox_path, postbox: @postbox

app/views/postboxes/new.html.slim
.introduction
  = image_tag "anopost_logo_main.svg", alt: "メインロゴ", class: "introduction__icon"
  p.introduction__text
    |AnoPostは匿名の投書箱を簡単に作成できる
    br
    |Webサービスです。
.introduction-images
  p.introduction-images__title AnoPostが解決できること
  p.introduction-images__text
    | 企業倫理やハラスメント行為などの問題を未然に防ぎたい会社と、
    br
    | 問題を認知しているけど、報復を恐れるなどの理由から記名で問題提起がしにくい従業員、
    br
    | 双方の課題を解決する、企業倫理ホットラインが作成できます。
  = image_tag "introduction_problem.png", alt: "ホットラインの説明", class: "introduction-images__item"
  p.introduction-images__text
    | ホットラインを作るためにはフォームに必要事項を入力するだけです。
    br
    | ユーザー登録やログインなどの面倒な操作は必要ありません。
    br
    | 投稿する人にURLを共有するだけで利用できます。
  = image_tag "introduction_hotline.png", alt: "ホットラインの説明", class: "introduction-images__item"

.three-points
  p.three-points__title AnoPostの3つの特徴
  .three-points-boxes
    .three-points-box
      .three-points-box__icon = icon "fas", "user-alt-slash"
      p.three-points-box__text 1.お手軽・便利
    .three-points-box
      .three-points-box__icon = icon "fas", "user-secret"
      p.three-points-box__text 2.完全匿名性
    .three-points-box
      .three-points-box__icon = icon "fab", "github"
      p.three-points-box__text 3.オープンソース
  ol.three-points-description
    li.three-points-description__item
      | ユーザー登録やログインは必要ありません。投書箱をとても簡単に作成できます。
    li.three-points-description__item
      | 投稿は匿名でおこなえます。誰が投稿したかは誰にもわかりません。
    li.three-points-description__item
      | GitHubでソースを公開しています。Herokuへのデプロイや機能改修が行えます。

- if @postbox.errors.any?
  .alert.alert-warning
    - @postbox.errors.full_messages.each do |msg|
      p.alert__message = msg
.postbox-form
  = render "form", from: :new, url: postboxes_path, postbox: @postbox

app/views/postboxes/show.html.slim
- @page_title = @postbox.title

.postbox
  p.postbox__title = @postbox.title
  p.postbox__description = safe_join(@postbox.description.split("\n"), tag(:br))
  .postbox-url
    p.postbox-url__url = "#{root_url}#{@postbox.uid}"
    .postbox-url__icon.js-copy-icon
      = icon "far", "copy"
      .postbox-url__description
  .url-explanation URLを共有された方が投書箱を利用できます。右側のアイコンをクリックするとコピーすることができます。
.post-form
  = render "/posts/form", from: :new, url: postbox_posts_path(postbox_uid: @postbox.uid), post: @post
.notice
  p.notice__text
    |投稿した内容は投書箱を作成した管理者のみが閲覧することができます。
    br
    |当サイトは投稿者の個人情報は保存しておりません。
    br
    |「発信者情報開示」の要請があった場合などを除き、発信者のIPアドレスなど
    br
    |各種個人情報を開示することはありません。

app/views/postboxs/new.html.slim
.introduction
  = image_tag("anopost_logo_main.svg", alt: "メインロゴ", class: "introduction__icon")
  p.introduction__text
    |AnoPostは匿名の投書箱を簡単に作成できる
    br
    |Webサービスです。

app/views/posts/_form.html.slim
= form_with model: post, url: postbox_posts_path(postbox_uid: @postbox.uid) do |f|
  .form-group
    = f.label "投稿内容", class: "form__label"
    p.form__sub-label 投稿内容を入力してください。
    = f.text_area :content, class: "form__text-area"

  .form-group
    = f.submit "匿名で投稿", class: "form__button--posts"

app/views/static_pages/about.html.slim
p.static-pages__title AnoPostとは
p.static-pages__text
  |AnoPostとは匿名の投書箱を作成できるWebサービスです。
  br
  |投書箱を企業倫理ホットラインなどに利用することができます。
  br
  |投書箱を作成する方も、投書を投稿する方もアカウント登録を必要とせず、
  br
  |いくつかの必要項目を入力するだけで、とても簡単に投書箱を作成することができます。
p.static-pages__sub-title 使い方
p.static-pages__sub-sub-title 管理者（投書箱を作成するユーザー）
.static-pages-block
  p.static-pages-block__text
    |TOPページから投書箱の「名前」「説明分」「パスワード」を
    br
    |入力し、画面下部の「作成」ボタンをクリックすることで、
    br
    |投書箱が作成されます。
    br
  = image_tag "about_create.png", class: "static-pages-block__image"
.static-pages-block
  p.static-pages-block__text
    |投書箱が作成されると画面の上部にURLが表示されます。
    br
    |URLを紛失すると同一の投書箱にアクセスできなくなります。
    br
    |十分にご注意ください。
    br
    |URLを配布することで、利用者も投書箱にアクセスできます。
  = image_tag "about_postbox.png", class: "static-pages-block__image"
.static-pages-block
  p.static-pages-block__text
    |管理者の方はヘッダーの「管理者ログイン」をクリックし、
    br
    |投書箱を作成した際の「パスワード」を入力することで、
    br
    |投稿された内容の閲覧や投書箱の設定内容を変更できます。
    br
    |URLを配布することで、利用者も投書箱にアクセスできます。
  = image_tag "about_login.png", class: "static-pages-block__image"
.static-pages-block
  p.static-pages-block__text
    |管理者の方は投稿内容を「JSON」「CSV」形式で
    br
    |ファイルに出力し、ダウンロードすることができます。
  = image_tag "about_export.png", class: "static-pages-block__image"
.static-pages-block
  p.static-pages-block__text
    |また、SlackのIncoming Webhook URLを設定することで、
    br
    |投稿があった際に投稿をSlackにも投稿することができます。
  = image_tag "about_slack.png", class: "static-pages-block__image"
p.static-pages__sub-sub-title 利用者（投書箱に投稿するユーザー）
.static-pages-block
  p.static-pages-block__text
    |管理者の方から共有されたURLにアクセスし、
    br
    |入力フォームに投稿内容を入力後、
    br
    |「匿名で投稿」ボタンをクリックすると投稿が完了します。
    br
  = image_tag "about_user.png", class: "static-pages-block__image"

app/views/static_pages/discramer.html.slim
p.static-pages__title 免責事項
p.static-pages__text
  |当サイトを利用し発生した損害について、当サイトは一切の賠償責任を負いません。
  br
  |当サイトを通じて得る情報等について、その完全性、正確性、確実性、有効性等に関して、いかなる保証も行いません。
  br
  |当サイトを利用し、第三者に損害を与えた場合、利用者は自己の責任と費用においてこれを賠償するものとします。
  br
  |当サイトが何らかの外的な要因により、データを破損等した場合、当サイトはその責任を負いません。
  br
  |当サイトは予告なしに、閉鎖させて頂くことがあります。

app/views/static_pages/privacy.html.slim
p.static-pages__title Cookieポリシー
p.static-pages__text
  |当サイトでは、一部のコンテンツについてCookieを利用しています。
  br
  |Cookieとは、サイトにアクセスした際にブラウザに保存される情報です。
  br
  |Cookie情報からは名前やメールアドレスなどの個人情報を特定をすることはできません。
  br
  |ブラウザの設定によりCookieの機能を無効にすることもできます。
  br
  |ただし、Cookieを無効にした場合、一部サービスが受けられない場合があることをご了承下さい。